# Generated by Django 3.1.7 on 2021-04-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sub', models.CharField(max_length=50)),
                ('pword', models.CharField(default=None, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sub', models.CharField(max_length=15)),
                ('exp', models.CharField(max_length=15)),
                ('pword', models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
